---

wheel_radius: 0.033
track_width: 0.16
collision_radius: 0.11
motor_cmd_to_radsec: 0.024
encoder_ticks_to_rad: 0.00153398
motor_cmd_max: [-256, 256]
slip_min: -0.02
slip_max: 0.02
basic_sensor_variance: 0
max_range: 10